export const sidebarData = {
  navMain: [
    {
      title: "Master",
      url: "#",
      items: [{}],
    },
  ],
  projects: [
    { name: "Dashboard", url: "/home" },
    { name: "Buyer", url: "/master/buyer" },
    { name: "Bag Type", url: "/master/bag-type" },
    { name: "Bank", url: "/master/bank" },
    { name: "Container Size", url: "/master/containersize" },
    { name: "Container Size", url: "/master/containersize" },
    { name: "Country", url: "/master/country" },
    { name: "Gr Code", url: "/master/grcode" },
    { name: "Marking", url: "/master/marking" },
    { name: "Order Type", url: "/master/order-type" },
    { name: "Payment Term", url: "/master/payment-term" },
    { name: "Port of Loading", url: "/master/port-of-loading" },
    { name: "Pre Recepit", url: "/master/pre-recepit" },
    { name: "Product", url: "/master/product" },
    { name: "Scheme", url: "/master/scheme" },
    { name: "Shipper", url: "/master/shipper" },
    { name: "Vessel", url: "/master/vessel" },
    { name: "Company", url: "/master/branch" },
    { name: "State", url: "/master/state" },
    { name: "Item", url: "/master/item" },
    { name: "Pre Carriage", url: "/master/precarriage" },
    { name: "Vendor", url: "/master/vendor" },
  ],
  userManagement: [
    { name: "User Management", url: "/userManagement" },
    { name: "UserType", url: "/user-type" },
    { name: "Setting", url: "/setting" },
  ],
};
